### ISSUE TITLE
Xcode 如何配置

### ISSUE THREAD

**Issue by wf1992** [xx-li/disable_screenshots#1]
环境：Xcode 11。6     flutter 1.12.13 hotfix9  
在你提示的新建了swift的Bridging-Header之后，仍旧提示Module 'disable_screenshots' not found，如何去配置呢

**Comment by xx-li** [comment]
正常情况，纯OC项目，创建swift文件时会提示生成bridge header，生成后就可以正常使用了。 可以清理缓存后重新编译试试。

**Comment by wf1992** [comment]
直接用源码了
